# Generated by Django 5.1.1 on 2026-02-01 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_alter_cart_user'),
        ('shop_app', '0004_transaction'),
    ]

    operations = [
    ]
